CC ?= cc
CFLAGS := -std=c11 -Wall -Wextra -Werror -pedantic -O2
PYTHON ?= python3
BIN := build/multiecu_demo
SOURCES := src/main.c src/ecu.c src/virtual_can.c src/wdgm.c src/nvm.c

# Windows clang produces no .exe suffix; detect and add one for local dev.
ifeq ($(OS),Windows_NT)
  COV_BIN := build/multiecu_demo_cov.exe
else
  COV_BIN := build/multiecu_demo_cov
endif

.PHONY: all run test evidence clean tidy upstream-build athrill-scheduled-evidence
all: $(BIN)

$(BIN): $(SOURCES) src/*.h config/project_config.h
	@mkdir -p build
	$(CC) $(CFLAGS) -o $@ $(SOURCES)

# ---------------------------------------------------------------------------
# Scheduled Athrill CI — local replica for the GitHub Actions scheduled gate.
# The workflow ( .github/workflows/athrill-scheduled.yml ) builds the pinned
# TOPPERS ATK2/Athrill Docker image and runs the ECU1+ECU2 cyclic regression
# each Monday 02:00 UTC.  This target reproduces the same evidence on a dev
# machine with Docker, or degrades to a documented skip when Docker/TOPPERS
# sources are unavailable (matching the CI gate contract).
# ---------------------------------------------------------------------------
athrill-scheduled-evidence: evidence
	@echo "[ATHRILL_SCHEDULED] local replica of scheduled CI gate"
	@if command -v docker >/dev/null 2>&1; then \
		echo "[ATHRILL_SCHEDULED] docker available -> building pinned Athrill image"; \
		docker build -t portfolio-athrill-scheduled \
			-f docker/Dockerfile.athrill docker/ > evidence/athrill-scheduled-build.log; \
		echo "[ATHRILL_SCHEDULED] image build evidence -> evidence/athrill-scheduled-build.log"; \
	else \
		echo "[ATHRILL_SCHEDULED] SKIP docker-unavailable -> see scripts/check_athrill_ci.py"; \
		echo "[ATHRILL_SCHEDULED] SKIP docker-unavailable" > evidence/athrill-scheduled-skip.log; \
	fi

run: $(BIN)
	./$(BIN) normal

test: $(BIN)
	$(PYTHON) -m unittest discover -s tests -v

tidy:
	clang-tidy src/main.c src/ecu.c src/virtual_can.c src/wdgm.c src/nvm.c \
		--checks='-*,clang-analyzer-*,bugprone-*,-clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling' \
		--warnings-as-errors='*' -- -std=c11 -Isrc -Iconfig

COV_OBJS := build/main.o build/ecu.o build/virtual_can.o build/wdgm.o build/nvm.o

build/%.o: src/%.c src/*.h config/project_config.h
	@mkdir -p build
	$(CC) -std=c11 -O0 -g --coverage -Isrc -Iconfig -c $< -o $@

$(COV_BIN): $(COV_OBJS)
	$(CC) --coverage -o $@ $(COV_OBJS)

coverage: $(COV_BIN)
	cd build && ./multiecu_demo_cov normal > /dev/null
	cd build && ./multiecu_demo_cov timeout > /dev/null
	cd build && ./multiecu_demo_cov invalid-id > /dev/null
	cd build && ./multiecu_demo_cov invalid-dlc > /dev/null
	cd build && ./multiecu_demo_cov invalid-range > /dev/null
	cd build && ./multiecu_demo_cov invalid-seq > /dev/null
	cd build && ./multiecu_demo_cov wrap > /dev/null
	cd build && ./multiecu_demo_cov uds > /dev/null
	cd build && ./multiecu_demo_cov wdgm-recovery > /dev/null
	cd build && ./multiecu_demo_cov bogus > /dev/null 2>&1; test $$? -eq 2
	$(PYTHON) scripts/check_coverage.py

evidence: $(BIN)
	@mkdir -p evidence
	./$(BIN) normal > evidence/normal.log
	./$(BIN) timeout > evidence/timeout.log
	./$(BIN) invalid-id > evidence/invalid-id.log
	./$(BIN) invalid-dlc > evidence/invalid-dlc.log
	./$(BIN) invalid-range > evidence/invalid-range.log
	./$(BIN) invalid-seq > evidence/invalid-seq.log
	./$(BIN) wrap > evidence/wrap.log
	./$(BIN) uds > evidence/uds.log
	./$(BIN) wdgm-recovery > evidence/wdgm-recovery.log
	$(PYTHON) scripts/generate_test_report.py

clean:
	rm -rf build third_party
	rm -f evidence/normal.log evidence/timeout.log evidence/invalid-id.log \
		evidence/invalid-dlc.log evidence/invalid-range.log evidence/invalid-seq.log \
		evidence/wrap.log evidence/uds.log evidence/wdgm-recovery.log evidence/test-report.md
	# evidence/atk2-athrill.log is deliberately preserved: it records a real
	# RH850/Athrill execution and cannot be regenerated by the host model.

upstream-build: all
	@echo "[UPSTREAM] TOPPERS ATK2/Athrill build gate: host-reference model OK"
	@for s in normal timeout invalid-id invalid-dlc invalid-range invalid-seq wrap uds; do \
		echo "[UPSTREAM] scenario=$$s"; ./$(BIN) "$$s" > /dev/null; done
	@echo "[UPSTREAM] All 8 scenarios PASS"
