CC ?= cc
CFLAGS := -std=c11 -Wall -Wextra -Werror -pedantic -O2
BIN := build/multiecu_demo
SOURCES := src/main.c src/ecu.c src/virtual_can.c

.PHONY: all run test evidence clean upstream-setup upstream-run
all: $(BIN)

$(BIN): $(SOURCES) src/*.h config/project_config.h
	@mkdir -p build
	$(CC) $(CFLAGS) -o $@ $(SOURCES)

run: $(BIN)
	./$(BIN) normal

test: $(BIN)
	python3 -m unittest discover -s tests -v

tidy:
	clang-tidy src/main.c src/ecu.c src/virtual_can.c \
		--checks='-*,clang-analyzer-*,bugprone-*,-clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling' \
		--warnings-as-errors='*' -- -std=c11 -Isrc -Iconfig

COV_OBJS := build/main.o build/ecu.o build/virtual_can.o

build/%.o: src/%.c src/*.h config/project_config.h
	@mkdir -p build
	$(CC) -std=c11 -O0 -g --coverage -Isrc -Iconfig -c $< -o $@

build/multiecu_demo_cov: $(COV_OBJS)
	$(CC) --coverage -o $@ $(COV_OBJS)

coverage: build/multiecu_demo_cov
	cd build && ./multiecu_demo_cov normal > /dev/null
	cd build && ./multiecu_demo_cov timeout > /dev/null
	cd build && ./multiecu_demo_cov invalid-id > /dev/null
	cd build && ./multiecu_demo_cov invalid-dlc > /dev/null
	cd build && ./multiecu_demo_cov invalid-range > /dev/null
	cd build && ./multiecu_demo_cov invalid-seq > /dev/null
	cd build && ./multiecu_demo_cov bogus > /dev/null 2>&1; test $$? -eq 2
	python3 scripts/check_coverage.py

evidence: $(BIN)
	@mkdir -p evidence
	./$(BIN) normal > evidence/normal.log
	./$(BIN) timeout > evidence/timeout.log
	./$(BIN) invalid-id > evidence/invalid-id.log
	./$(BIN) invalid-dlc > evidence/invalid-dlc.log
	./$(BIN) invalid-range > evidence/invalid-range.log
	./$(BIN) invalid-seq > evidence/invalid-seq.log
	python3 scripts/generate_test_report.py

upstream-setup:
	bash scripts/setup_upstream.sh

upstream-run:
	bash scripts/run_atk2_demo.sh

clean:
	rm -rf build third_party
	rm -f evidence/normal.log evidence/timeout.log evidence/invalid-id.log \
		evidence/invalid-dlc.log evidence/invalid-range.log evidence/invalid-seq.log \
		evidence/test-report.md
	# evidence/atk2-athrill.log is deliberately preserved: it records a real
	# RH850/Athrill execution and cannot be regenerated by the host model.
